<section class="categories">
<div class="column col-md-4 col-sm-4">
<div class = "category">
<a class = "black" href = "philosophy.html"><h2><span class="">Philosophy</span></h2></a>
<ul class="links">
$philosophylinks:linklist()$
</ul>
<div class="description"><a href="http://www.faburls.com/marketplaces/" class="showall">Show all URLs</a></div>
</div>
<div class = "category">
<a class = "black" href = "rust.html"><h2><span class="">Rust</span></h2></a>
<ul class="links">
$rustlinks:linklist()$
</ul>
</div>
<div class = "category">
<a class = "black" href = "spirituality.html"><h2><span class="">Spirituality</span></h2></a>
<ul class="links">
$spiritualitylinks:linklist()$
</ul>
</div>
</div>
<div class="column col-md-4 col-sm-4">
<div class = "category">
<a class = "black" href = "business.html"><h2><span class="">Business</span></h2></a>
<ul class="links">
$businesslinks:linklist()$
</ul>
</div>
<div class = "category">
<a class = "black" href = "conrod.html"><h2><span class="">Conrod</span></h2></a>
<ul class="links">
$conrodlinks:linklist()$
</ul>
</div>
<div class = "category">
<a class = "black" href = "philosophy.html"><h2><span class="">Philosophy</span></h2></a>
<ul class="links">
$philosophylinks:linklist()$
</ul>
</div>
</div>
<div class="column col-md-4 col-sm-4">
<div class = "category">
<a class = "black" href = "haskell.html"><h2><span class="">Haskell</span></h2></a>
<ul class="links">
$haskelllinks:linklist()$
</ul>
</div>
<div class = "category">
<a class = "black" href = "metalearning.html"><h2><span class="">Metalearning</span></h2></a>
<ul class="links">
$metalearninglinks:linklist()$
</ul>
</div>
<div class = "category">
<a class = "black" href = "philosophy.html"><h2><span class="">Philosophy</span></h2></a>
<ul class="links">
$philosophylinks:linklist()$
</ul>
</div>
</div>
</section>